name: hola mundo

on:
  workflow_dispatch:
    
  # schedule:
  #   - cron: "*/5 * * * *" # se ejecuta cada 5 segundos
  # push:
  #   branches:
  #     - main
  pull_request:
      branches:
        -main
jobs:
  saludar:
    runs-on: ubuntu-latest
    steps:
      - name: Muestra mensaje hola mundo
        run: echo "Hola mundo Luis Carlos"
        
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Listar los archivos del repositorio
        run: |
          echo "El repositorio ${{ github.repository }} contiene los siguientes arhichos:"
          tree
          
